## Nama Penulis : ...
## Kelas        : ...
## Lab 1 - Circle Area & Perimeter

# Import math [BONUS]
...

# Minta input jari-jari
jari_jari = ...

# Masukkan nilai jari-jari tersebut ke dalam rumus luas dan keliling
# kemudian tampung hasilnya ke dalam variable
luas = ...
keliling = ...

# Cetak hasilnya
print(...)